FROM node:8.16.0-alpine AS frontend-build

ADD . /app
WORKDIR /app

# install frontend
RUN npm install -g yarn \
	&& yarn install

RUN npm run build:prod

FROM nginx:1.15

COPY --from=frontend-build /app/dist /app/dist
COPY --from=frontend-build /app/conf/crawlab.conf /etc/nginx/conf.d
